spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: task_user
    password: task_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

jwt:
  secret: "change-me-please-32-bytes-minimum-change-me-please"
  expiration: 86400000